// Generated by CoffeeScript 1.3.3

var chai = require('chai');
chai.should();

var assert = require('chai').assert;

describe('syslog', function() {
  it('should provide instances', function() {
    return (function() {
      var syslog;
      return syslog = require('../lib/syslog');
    }).should.not["throw"]('');
  });

  it('should have a log function', function() {
    var syslog;
    syslog = require('../lib/syslog');
    return (function() {
      return syslog.log(syslog.LOG_INFO, 'Test');
    }).should.not["throw"]('');
  });

  return it('should be a singleton', function() {
    var syslog1, syslog2;
    syslog1 = require('../lib/syslog');
    syslog2 = require('../lib/syslog');
    return assert.strictEqual(syslog1, syslog2);
  });
});
