// Generated by CoffeeScript 1.3.3
/* A2R Index Server
*/

var mongoose = require('mongoose') ;
var express = require('express');

var syslog = require('./lib/syslog').getInstance();
var config = require('./lib/configloader').load('index.config');

var sessions = mongoose.model('Sessions', require('./models/models.js').Sessions) ;

//ToDo: read settings from config
mongoose.connect('mongodb://localhost/a2r_index') ;

index_web = express.createServer();
index_web.set('view engine', 'jade');
index_web.use(express["static"](__dirname + '/public'));
index_web.use(express.bodyParser()) ;

index_web.get('/show.:format?', function(req, res) {
  sessions.find({}, function(err, docs) {
    if (err) {
      return syslog.log(syslog.LOG_ERROR, err) ;
    } else {
      if (req.params.format == "json") {
        // ToDo: never send the token
        return res.json(docs) ;
      } else {
        return res.render('index', { sessions: docs}) ;
      }
    }
  }) ;
});

index_web.get('/show/:id.:format?', function(req, res) {
  sessions.findById(req.params.id, function(err, doc) {
    if (err) {
      return syslog.log(syslog.LOG_ERROR, err) ;
    } else {
      if (req.params.format == "json") {
        return res.json(doc) ;
      } else {
        return res.render('show', { session: doc }) ;
      }
    }
  }) ;
}) ;

index_web.listen(config['index_web_port']);

console.log('Server running');
syslog.log(syslog.LOG_INFO, 'starting index server on port ' + config['notify_server_port']);
